export const TABLE_OF_CONTENTS = [
  { id: "overview", label: "Overview" },
  { id: "why-choose-k666", label: "Why Choose K666?" },
  { id: "what-is-k666", label: "What is K666?" },
  { id: "key-features", label: "Key Features of K666 Game Earning App" },
  { id: "games-to-play", label: "Games to Play on K666 Game App" },
  { id: "how-to-get-started", label: "How to Get Started on K666 Game App?" },
  { id: "registration-login", label: "K666 Registration and Login Process" },
  { id: "download-install", label: "How to Download and Install K666 APK?" },
  { id: "bonuses-promotions", label: "K666 Bonuses and Promotions" },
  { id: "become-k666-agent", label: "How to Become K666 Agent" },
  { id: "payment-methods", label: "Payment Methods for Deposit and Withdrawals" },
  { id: "safe-and-legal", label: "Is K666 Safe and Legal?" },
  { id: "pros-and-cons", label: "Pros and Cons" },
  { id: "experience-reviews", label: "Personal Experience and User Reviews" },
  { id: "conclusion", label: "Conclusion" },
  { id: "faqs", label: "FAQs" },
] as const;
