export const TABLE_OF_CONTENTS = [
  { id: "overview-of-k666", label: "Overview Of K666" },
  { id: "what-is-k666-game", label: "What is the K666 Game?" },
  { id: "top-key-features", label: "Top Key Features of K666 Download APK" },
  { id: "k666-app-screenshots", label: "K666 App Screenshots" },
  { id: "download-install-guide", label: "K666 Game Download & Install – Easy & Updated Guide 2026" },
  { id: "login-sign-up", label: "K666 Login & Sign Up – Simple Steps" },
  { id: "trend-pakistan-2026", label: "Reasons Behind the Trend of K666 APK in Pakistan in 2026" },
  { id: "deposit-withdrawal", label: "K666 Deposit & Withdrawal – Easy Guide For New Players" },
  { id: "popular-games", label: "Popular Games You Can Play Inside the K666 Game" },
  { id: "best-earning-game", label: "Is The K666 Game The Best Earning Game in Pakistan?" },
  { id: "referral-program", label: "K666 Referral Program Fully Explained" },
  { id: "safety-tips", label: "Tips To Play the K666 Game Safely" },
  { id: "pros-and-cons", label: "Pros and Cons Of K666" },
  { id: "my-experience", label: "My Experience With K666 Online Earning Game" },
  { id: "user-reviews", label: "User Reviews" },
  { id: "conclusion", label: "Conclusion" },
  { id: "faqs", label: "FAQs" },
] as const;
